version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdbname

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bookings
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: